#pragma once

#define LAYER_CAM					L"Layer_Cam"
#define LAYER_DEBUG					L"Layer_Debug"
#define LAYER_STORYPLAYER			L"Layer_StoryPlayer"
#define LAYER_PLAYER				L"Layer_Player"
#define LAYER_MONSTER				L"Layer_Monster"
#define LAYER_ITEM					L"Layer_Item"
#define LAYER_PROJECTILE			L"Layer_Projectile"
#define LAYER_TESTPLAYER			L"Layer_TestPlayer"
#define LAYER_UI					L"Layer_UI"
#define LAYER_UIMODEL				L"Layer_UIModel"
#define LAYER_LINES					L"Layer_Lines"
#define LAYER_ANIMAL				L"Layer_Animal"
#define LAYER_NPC					L"Layer_NPC"
#define LAYER_QUEST					L"Layer_Quset"
#define LAYER_MAP					L"Layer_Map"
#define	LAYER_EFFECT				L"Layer_Effect"
#define LAYER_MAPOBJ				L"Layer_MapObj"
#define LAYER_MAPGROUND				L"Layer_MapGround"
#define LAYER_TRAIL					L"Layer_Trail"
#define LAYER_SWORD				    L"Layer_Sword"
#define LAYER_SHEATH				L"LAYER_Sheath"
// 오니 레이어 
#define LAYER_ONI1					L"Layer_Oni_1"
#define LAYER_ONI2					L"Layer_Oni_2"
#define LAYER_ONI3					L"Layer_Oni_3"
#define LAYER_ONI4					L"Layer_Oni_4"