#pragma once

#define COM_SHADER L"Comp_Shader"
#define COM_TEXTURE L"Com_Texture"
#define COM_VIBUFFER L"Com_VIBuffer"
#define COM_TRANSFORM L"Com_Tramsform"
#define COM_RENDERER L"Com_Rederer"
#define COM_MODEL L"Com_Model"
#define COM_INSTANCEMODEL L"Com_InstanceModel"
#define COM_NAVIGATION L"Com_Navigation"
#define COM_ANIMATOR L"Com_Animator"
#define COM_COLLIDER_HIT L"Com_Collider_Hit"
#define COM_COLLIDER_AABB L"Com_Collider_AABB"
#define COM_COLLIDER_OBB L"Com_Collider_OBB"
#define COM_COLLIDER_SPHERE L"Com_Collider_SPHERE"
#define COM_COLLIDER_PREV_OBB L"Com_Coliider_Prev_OBB"
#define COM_COLLIDER_RECOGNIZE L"Com_Collider_Recognize"
#define COM_COLLIDER_MONSTER L"Com_Collider_Monster"
#define COM_COLLIDER_ATTACK L"Com_Collider_Attack"
#define COM_COLLIDER_ANIMATTACK L"Com_Collider_AnimAttack"
#define COM_COLLIDER_LIMIT L"Com_Collider_Limit"